# Generated by Django 4.2.13 on 2026-05-20 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="classification",
            field=models.CharField(default="General", max_length=100),
        ),
        migrations.AddField(
            model_name="document",
            name="risk_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="risk_status",
            field=models.CharField(default="Clean", max_length=50),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Viewer", "Viewer"),
                            ("Editor", "Editor"),
                            ("Admin", "Admin"),
                        ],
                        default="Viewer",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
