# Generated by Django 4.2.13 on 2026-05-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_backend",
            "0002_document_classification_document_risk_details_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("otp", models.CharField(max_length=6)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Viewer", "Viewer"),
                            ("Editor", "Editor"),
                            ("Admin", "Admin"),
                        ],
                        default="Viewer",
                        max_length=20,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("HR", "HR"),
                            ("Legal", "Legal"),
                            ("Finance", "Finance"),
                            ("Technical", "Technical"),
                            ("General", "General"),
                        ],
                        default="General",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_verified", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="document",
            name="department",
            field=models.CharField(
                choices=[
                    ("HR", "HR"),
                    ("Legal", "Legal"),
                    ("Finance", "Finance"),
                    ("Technical", "Technical"),
                    ("General", "General"),
                ],
                default="General",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="department",
            field=models.CharField(
                choices=[
                    ("HR", "HR"),
                    ("Legal", "Legal"),
                    ("Finance", "Finance"),
                    ("Technical", "Technical"),
                    ("General", "General"),
                ],
                default="General",
                max_length=20,
            ),
        ),
    ]
