# Generated by Django 4.2.13 on 2026-05-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0004_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enforce_globally', models.BooleanField(default=False)),
                ('provider', models.CharField(default='gemini', max_length=50)),
                ('model', models.CharField(default='gemini-1.5-flash', max_length=100)),
                ('temperature', models.FloatField(default=0.3)),
                ('k', models.IntegerField(default=4)),
                ('groq_api_key', models.CharField(blank=True, max_length=255)),
                ('gemini_api_key', models.CharField(blank=True, max_length=255)),
                ('openai_api_key', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
